name: musicccc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  on_audio_query: ^2.9.0
  permission_handler: ^12.0.1
  just_audio: ^0.10.5
  provider: ^6.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


  fonts:
     - family: Manrope
       fonts:
         - asset: assets/fonts/Manrope-Regular.ttf
         - asset: assets/fonts/Manrope-Bold.ttf
           weight: 700
